language: python
python:
  - "3.6"
# command to install dependencies

install:
#  - pip install -r requirements.txt
  - sudo apt-get install graphviz
  - pip install codecov
## command to run tests

script:
  - python setup.py test
  - codecov
